name: Publish

on:
  release:
    types:
    - created

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - name: Run Publish
        if: success()
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
